name: source-location
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - numpy
  - xarray
  - geopandas
  - pyproj
  - shapely
  - matplotlib
  - ca-certificates
  - openssl
  - findiff
  - certifi
